Repository champtc/opencti, pull requests merged in 2021-12, with the labels that each got.

#62 bug 4274 fixed
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreation.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCreation.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEditionContainer.js
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectHeader.js
Labels: bug

#51 bug 4263 fixed
  opencti-platform/opencti-front/schema/introspection.graphql
  opencti-platform/opencti-front/src/components/list_cards/CyioListCards.js
  opencti-platform/opencti-front/src/components/list_lines/CyioListLines.js
  opencti-platform/opencti-front/src/private/components/assets/Devices.js
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.js
  opencti-platform/opencti-front/src/private/components/settings/ItAssetFilters.js
  opencti-platform/opencti-front/src/private/components/settings/ItAssetListQuery.js
  opencti-platform/opencti-front/src/utils/ListParameters.js
  opencti-platform/opencti-front/src/utils/Localization.js
  opencti-platform/opencti-graphql/schema_merge.js
Labels: bug

#52 bug 4267 fixed
  opencti-platform/opencti-front/src/private/components/assets/Network.js
Labels: bug

#53 bug 4278 fixed
  opencti-platform/opencti-front/src/private/components/assets/Software.js
  opencti-platform/opencti-front/src/private/components/common/lists/Filters.js
  opencti-platform/opencti-front/src/utils/Localization.js
Labels: bug

#54 Secutree asset 4261 bugfix
  opencti-platform/opencti-front/src/components/ItemIcon.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceLine.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DevicesCards.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DevicesLines.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkCards.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkLines.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCards.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareLines.js
Labels: bug

#58 Secutree asset 4290 bugfix
  opencti-platform/opencti-front/src/components/ItemIcon.js
  opencti-platform/opencti-front/src/private/components/assets/devices/Device.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreationDetails.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEdition.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionDetails.js
  opencti-platform/opencti-front/src/private/components/assets/devices/Root.js
  opencti-platform/opencti-front/src/private/components/assets/network/Network.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkDetails.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkEdition.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/network/Root.js
  opencti-platform/opencti-front/src/private/components/assets/software/Root.js
  opencti-platform/opencti-front/src/private/components/assets/software/Software.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareDetails.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEdition.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEditionContainer.js
  opencti-platform/opencti-front/src/private/components/common/form/InstalledAsset.js
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetEditionOverview.js
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetOverview.js
Labels: bug

#73 Task 4352
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
  opencti-platform/opencti-front/src/utils/percentage.js
Labels: bug, enhancement

#72 bug 4405 fixed
  opencti-platform/opencti-front/src/private/components/analysis/external_references/CyioAddExternalReferences.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreationDetails.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreationOverview.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionDetails.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreationDetails.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCreationDetails.js
  opencti-platform/opencti-front/src/private/components/common/form/Ports.js
  opencti-platform/opencti-front/src/private/components/common/form/Protocols.js
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetCreationOverview.js
  opencti-platform/opencti-front/src/private/components/vsac/Compare.js
Labels: bug

#77 Task 4235
  opencti-platform/opencti-front/src/private/Index.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioCoreObjectOrCyioCoreRelationshipNoteCard.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/StixCoreObjectOrStixCoreRelationshipNoteCard.js
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.js
  opencti-platform/opencti-front/src/private/components/nav/UserPreferencesModal.js
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
  opencti-platform/opencti-front/src/private/components/vsac/modals/VulnerabilityScan.js
  opencti-platform/opencti-front/src/relay/environment.js
Labels: enhancement

#78 updated resolvers and Stardog datasource to detect and report back er…
  opencti-platform/opencti-graphql/src/cyio/schema/assets/asset-common/resolvers.js
  opencti-platform/opencti-graphql/src/cyio/schema/assets/computing-device/resolvers.js
  opencti-platform/opencti-graphql/src/cyio/schema/assets/network/resolvers.js
  opencti-platform/opencti-graphql/src/cyio/schema/assets/network/sparql-query.js
  opencti-platform/opencti-graphql/src/cyio/schema/assets/software/resolvers.js
  opencti-platform/opencti-graphql/src/datasources/stardog.js
Labels: enhancement

#75 AB#4408 X-Cyio-Client inclusion for GraphQL requests.
  opencti-platform/opencti-front/src/relay/environment.js
  opencti-platform/opencti-front/src/relay/environmentDarkLight.js
  opencti-platform/opencti-graphql/src/graphql/graphql.js
Labels: enhancement

#80 Fixed LeftBar Org HardCoded Value
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.js
  opencti-platform/opencti-front/src/private/components/nav/UserPreferencesModal.js
Labels: bug

#76 bug 4411 fixed
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreationDetails.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionDetails.js
  opencti-platform/opencti-front/src/private/components/common/form/InstalledAsset.js
Labels: bug

#74 Secutree asset 4403 task
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioCoreObjectOrCyioCoreRelationshipNoteCard.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioCoreObjectOrCyioCoreRelationshipNotes.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioNoteCreation.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioNoteEditionContainer.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioNoteEditionOverview.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioNotePopover.js
Labels: enhancement

#81 Secutree asset all bugfixes
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCard.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreationDetails.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionDetails.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreation.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreationDetails.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionDetails.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCreation.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEditionContainer.js
  opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetEditionOverview.js
Labels: bug
