Repository champtc/opencti, pull requests merged in 2022-03, with the labels that each got.

#182 AB#4780 Keycloak GraphQL Integration
  opencti-platform/opencti-graphql/package.json
  opencti-platform/opencti-graphql/src/graphql/authDirectives.graphql
  opencti-platform/opencti-graphql/src/graphql/graphql.js
  opencti-platform/opencti-graphql/src/http/httpPlatform.js
  opencti-platform/opencti-graphql/src/initialization.js
  opencti-platform/opencti-graphql/src/service/keycloak.js
  opencti-platform/opencti-graphql/yarn.lock
Labels: enhancement

#186 fix: updates to the analysis summary view.
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
Labels: bug, enhancement

#187 fix: ensuring the user input for the scan name is applied when submit…
  opencti-platform/opencti-front/src/private/components/vsac/modals/VulnerabilityScan.js
Labels: bug

#198 AB#4863 Feature Flagging
  opencti-platform/opencti-front/src/app.js
  opencti-platform/opencti-front/src/components/feature/FeatureFlag.js
  opencti-platform/opencti-front/src/components/feature/FeatureProvider.js
  opencti-platform/opencti-front/src/private/Index.js
  opencti-platform/opencti-front/src/private/components/nav/LeftBar.js
Labels: enhancement

#220 Gripes
  opencti-platform/opencti-front/package-lock.json
  opencti-platform/opencti-front/yarn.lock
  opencti-platform/opencti-graphql/package-lock.json
  package-lock.json
Labels: enhancement
