Repository champtc/opencti, pull requests merged in 2022-04, with the labels that each got.

#230 fix: adding the notify checkbox for the new analysis modal
  opencti-platform/opencti-front/src/private/components/vsac/modals/NewAnalysis.js
  opencti-platform/opencti-front/src/private/components/vsac/modals/VulnerabilityScan.js
Labels: enhancement

#236 Ab#4896
  Jenkinsfile
  opencti-platform/opencti-graphql/yarn.lock
Labels: enhancement

#242 fix: correcting the new vulnerability scan submit button enable state
  opencti-platform/opencti-front/src/private/components/vsac/modals/VulnerabilityScan.js
Labels: bug, enhancement

#248 AB#4996
  opencti-platform/opencti-front/src/components/list_cards/CyioListCards.js
  opencti-platform/opencti-front/src/components/list_lines/CyioListLines.js
Labels: bug

#271 AB#5048
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
Labels: bug

#279 AB#5050 fix: redoing the scan sorting algo and fixing the sort by label per s…
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
Labels: bug

#291 AB#4920 - Updated risk to provide ordering and filtering
  opencti-platform/opencti-graphql/src/cyio/schema/global/global-utils.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/assessment-common/resolvers/observation.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/assessment-common/resolvers/oscalTask.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/assessment-common/resolvers/risk.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/assessment-common/resolvers/riskResponse.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/assessment-common/resolvers/sparql-query.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/assessment-common/typeDefs.graphql
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/poam/resolvers/poam.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/poam/resolvers/poamItem.js
  opencti-platform/opencti-graphql/src/cyio/schema/risk-assessments/riskUtils.js
Labels: enhancement

#284 AB#5022
  opencti-platform/opencti-front/src/private/components/common/form/LoggedBy.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskLogCreation.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskTracking.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskTrackingLine.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskTrackingLines.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskTrackingPopover.js
Labels: bug

#287 AB#5036
  opencti-platform/opencti-front/src/private/components/analysis/external_references/CyioCoreObjectExternalReferencesLines.js
  opencti-platform/opencti-front/src/private/components/analysis/external_references/CyioExternalReferenceEdition.js
  opencti-platform/opencti-front/src/private/components/analysis/external_references/CyioExternalReferencePopover.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioCoreObjectOrCyioCoreRelationshipNoteCard.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioNoteCreation.js
  opencti-platform/opencti-front/src/private/components/analysis/notes/CyioNoteEditionOverview.js
  opencti-platform/opencti-front/src/private/components/assets/devices/Device.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCard.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/devices/DeviceLine.js
  opencti-platform/opencti-front/src/private/components/assets/network/Network.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkCard.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/network/NetworkLine.js
  opencti-platform/opencti-front/src/private/components/assets/software/Software.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCard.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEditionContainer.js
  opencti-platform/opencti-front/src/private/components/assets/software/SoftwareLine.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/Risk.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/RiskAnalysisEditionContainer.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/remediations/RelatedTasksLines.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/remediations/Remediation.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/remediations/RemediationEditionContainer.js
  opencti-platform/opencti-front/src/private/components/riskAssessment/risks/remediations/RequiredResourcesLines.js
Labels: bug

#297 AB#5049 Fixing lingering popover
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
Labels: bug, enhancement

#315 Fixing explore results button not forwarding to scan results
  opencti-platform/opencti-front/src/private/components/vsac/Scans.js
Labels: bug
